import { Inter, Outfit } from 'next/font/google';
import './globals.css';
import ScrollToTopButton from './Components/ScrollToTopButton';
import Navbar from './Components/Navbar';
import { getMainMenu } from '../lib/api/menuAPI';

const inter = Inter({ subsets: ['latin'] });
const outfit = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Added revalidation
// export const revalidate = 0

export default async function RootLayout({ children }) {
  console.log(process.env.SITE_URL_ENDPOINT, 'page server');

  const menuData = await getMainMenu();
  console.log(menuData, 'menu data.....');

  return (
    <html lang="en">
      <body className={`${outfit.className} ${inter.className}`}>
        {/*  */}
        <Navbar menuData={menuData} />
        {children}
        <ScrollToTopButton />
      </body>
    </html>
  );
}
